const clinics = ['Клиника «Семейная»','Медцентр «Южный»','Клиника «Новая медицина»'];
const doctors = ['Наталья Сергеева','Михаил Орлов','Елена Морозова','Дарья Ким'];
const telegram = window.Telegram?.WebApp || null;
if (telegram) {
  telegram.ready();
  telegram.expand();
  telegram.setHeaderColor('#ffffff');
  telegram.setBackgroundColor('#f4f8fa');
  document.documentElement.classList.add('telegram-webapp');
}
const initialRows = [
  {id:'Н-1042',name:'Анна К.',last:'3184',clinic:clinics[0],doctor:doctors[0],date:'2026-09-20',visit:'2026-09-22',status:'sent',reward:1500},
  {id:'Н-1041',name:'Виктор П.',last:'8291',clinic:clinics[0],doctor:doctors[0],date:'2026-09-18',visit:'2026-09-19',status:'verified',reward:1500},
  {id:'Н-1040',name:'Марина С.',last:'5027',clinic:clinics[1],doctor:doctors[1],date:'2026-09-17',visit:'2026-09-20',status:'arrived',reward:1500},
  {id:'Н-1039',name:'Ольга М.',last:'7180',clinic:clinics[2],doctor:doctors[2],date:'2026-09-15',visit:'2026-09-17',status:'dispute',reward:1500},
  {id:'Н-1038',name:'Игорь Л.',last:'0924',clinic:clinics[0],doctor:doctors[0],date:'2026-09-12',visit:'2026-09-14',status:'verified',reward:1500},
  {id:'Н-1037',name:'Светлана Р.',last:'6602',clinic:clinics[1],doctor:doctors[3],date:'2026-09-11',visit:'2026-09-16',status:'verified',reward:1500},
  {id:'Н-1036',name:'Павел Т.',last:'3947',clinic:clinics[0],doctor:doctors[0],date:'2026-09-09',visit:'2026-09-12',status:'cancelled',reward:1500},
  {id:'Н-1035',name:'Елена Д.',last:'2468',clinic:clinics[2],doctor:doctors[2],date:'2026-09-06',visit:'2026-09-10',status:'verified',reward:1500},
  {id:'Н-1034',name:'Роман Б.',last:'5601',clinic:clinics[1],doctor:doctors[1],date:'2026-09-04',visit:'2026-09-08',status:'verified',reward:1500}
];
const rows = initialRows.map(x=>({...x}));
const state={role:'partner',tab:'home',filters:{clinic:'all',doctor:'all',status:'all',from:'2026-09-01',to:'2026-09-30',query:''}};
const roleInfo={partner:{name:'Наталья Сергеева',org:clinics[0],avatar:'Н',title:'Врач клиники-партнёра',nav:[['home','Обзор','◫'],['new','Направить','＋'],['patients','Пациенты','▤'],['payouts','Вознаграждение','◈']]},doctor:{name:'Алексей Воронцов',org:'ГлазЦентр · врач',avatar:'А',title:'Врач ГлазЦентра',nav:[['home','Обзор','◫'],['queue','Пациенты','▤'],['reconcile','Сверка','☷']]},admin:{name:'Мария Белова',org:'ГлазЦентр · администратор',avatar:'М',title:'Администратор',nav:[['home','Обзор','◫'],['patients','Направления','▤'],['reconcile','Сверка','☷'],['payouts','Выплаты','◈']]}};
const statusText={sent:'Направлен',arrived:'Пришёл · сверить',verified:'Подтверждён',dispute:'Расхождение',cancelled:'Не пришёл'};
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=n=>new Intl.NumberFormat('ru-RU').format(n)+' ₽';
const day=d=>new Intl.DateTimeFormat('ru-RU',{day:'numeric',month:'short'}).format(new Date(d+'T12:00:00'));
const roleRows=()=>state.role==='partner'?rows.filter(r=>r.doctor===doctors[0]):rows;
const count=(arr,status)=>arr.filter(r=>r.status===status).length;
const confirmed=arr=>arr.filter(r=>r.status==='verified');
const el=id=>document.getElementById(id);
function toast(message){const node=el('toast');node.textContent=message;node.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>node.classList.remove('show'),3300)}
function setRole(role){state.role=role;state.tab='home';state.filters={clinic:'all',doctor:'all',status:'all',from:'2026-09-01',to:'2026-09-30',query:''};el('roleMenu').classList.add('hidden');el('roleButton').setAttribute('aria-expanded','false');render()}
function setTab(tab){state.tab=tab;render();window.scrollTo({top:0,behavior:'smooth'})}
function syncTelegramBackButton(){if(!telegram)return;if(state.tab==='home')telegram.BackButton.hide();else telegram.BackButton.show()}
function nav(){const info=roleInfo[state.role];el('roleName').textContent=info.name;el('roleOrg').textContent=info.org;el('roleAvatar').textContent=info.avatar;for(const id of ['nav','mobileNav'])el(id).innerHTML=info.nav.map(([key,label,icon])=>`<button class="nav-button ${state.tab===key?'active':''}" data-tab="${key}" ${state.tab===key?'aria-current="page"':''}><span class="nav-icon">${icon}</span><span>${label}</span></button>`).join('')}
function header(title,sub,action='',kicker='КАБИНЕТ ПАРТНЁРОВ'){return `<div class="mobile-role">${roleInfo[state.role].title}</div><div class="page-header"><div><div class="eyebrow">${kicker}</div><h1>${title}</h1><p>${sub}</p></div>${action}</div>`}
function stat(label,value,note='',emphasis=false){return `<div class="stat ${emphasis?'emphasis':''}"><span>${label}</span><strong>${value}</strong><small>${note}</small></div>`}
function badge(s){return `<span class="status ${s}">${statusText[s]}</span>`}
function table(list,mode='view'){if(!list.length)return '<div class="empty">По выбранным условиям записей нет. Измените фильтры.</div>';return `<div class="table-wrap"><table class="data-table"><thead><tr><th>Пациент / №</th><th>Клиника / врач</th><th>Направлен</th><th>Визит</th><th>Статус</th>${mode==='admin'||mode==='doctor'?'<th>Действие</th>':''}</tr></thead><tbody>${list.map(r=>`<tr><td><strong>${esc(r.name)}</strong><div class="person-meta">${esc(r.id)} · •••• ${esc(r.last)}</div></td><td><strong>${esc(r.clinic)}</strong><div class="person-meta">${esc(r.doctor)}</div></td><td>${day(r.date)}</td><td>${day(r.visit)}</td><td>${badge(r.status)}</td>${mode==='admin'?`<td>${r.status==='arrived'?`<button class="table-action" data-action="verify" data-id="${r.id}">Сверить</button>`:r.status==='dispute'?`<button class="table-action" data-action="resolve" data-id="${r.id}">Разобрать</button>`:'—'}</td>`:mode==='doctor'?`<td>${r.status==='sent'?`<button class="table-action" data-action="arrive" data-id="${r.id}">Отметить приход</button>`:'—'}</td>`:''}</tr>`).join('')}</tbody></table></div>`}
function overview(){const list=roleRows();const isPartner=state.role==='partner';const isDoctor=state.role==='doctor';const title=isPartner?'Добрый день, Наталья':isDoctor?'Направленные пациенты':'Обзор партнёрской программы';const subtitle=isPartner?'Ваши направления и подтверждённые визиты за сентябрь 2026 года.':isDoctor?'Отметьте фактический приход после проверки визита.':'Поток пациентов, сверка визитов и начисления за сентябрь 2026 года.';const action=isPartner?'<button class="btn btn-primary" data-tab="new">＋ Направить пациента</button>':`<button class="btn btn-outline" data-tab="${isDoctor?'queue':'reconcile'}">${isDoctor?'Открыть список':'Открыть сверку'} →</button>`;
const stats=isPartner?[stat('Направлено',list.length,'За выбранный месяц'),stat('Пришли',count(list,'verified')+count(list,'arrived'),'Включая ожидающие сверки'),stat('Подтверждено',count(list,'verified'),'Основание для выплаты'),stat('К выплате',money(confirmed(list).length*1500),'Тестовая ставка 1 500 ₽',true)]:isDoctor?[stat('Всего направлений',list.length,'От клиник-партнёров'),stat('Ожидают визита',count(list,'sent'),'По направлению'),stat('Пришли',count(list,'arrived')+count(list,'verified'),'Отмечены в системе'),stat('Нужна сверка',count(list,'arrived')+count(list,'dispute'),'Записи с вопросами',true)]:[stat('Направлений',list.length,'Сентябрь 2026'),stat('Пришли',count(list,'arrived')+count(list,'verified'),'Отмечен приход'),stat('Подтверждено',count(list,'verified'),'Для начисления'),stat('Сумма выплат',money(confirmed(list).length*1500),'По подтверждённым визитам',true)];
const recent=isPartner?list.slice(0,4):list.filter(r=>['sent','arrived','dispute'].includes(r.status)).slice(0,5);return header(title,subtitle,action)+`<div class="grid-stats">${stats.join('')}</div><div class="columns"><section class="card"><div class="card-head"><div><h2>${isPartner?'Мои направления':isDoctor?'Ближайшие и спорные визиты':'Требуют внимания'}</h2><p class="sub">${isPartner?'Последние отправленные пациенты':'Сведения для проверки'}</p></div><button class="text-button" data-tab="${isPartner?'patients':isDoctor?'queue':'reconcile'}">Все записи →</button></div>${table(recent,isDoctor?'doctor':isPartner?'view':'admin')}</section><section class="card"><h2>${isPartner?'Как начисляется вознаграждение':isDoctor?'Что делать при визите':'Порядок сверки'}</h2><p class="sub">Одна цепочка для всех участников</p><div class="steps"><div class="step"><span class="step-num">1</span><div><b>Врач создаёт направление</b><p>Пациент появляется в общем списке с привязкой к клинике и врачу.</p></div></div><div class="step"><span class="step-num">2</span><div><b>ГлазЦентр отмечает приход</b><p>Фактический визит проверяется по внутренней записи.</p></div></div><div class="step"><span class="step-num">3</span><div><b>Администратор подтверждает</b><p>Только подтверждённый визит участвует в расчёте выплаты.</p></div></div></div></section></div>`}
function newReferral(){return header('Новое направление','Заполните данные для поиска записи при фактическом визите.')+`<div class="columns"><section class="card"><div class="card-head"><div><h2>Данные направления</h2><p class="sub">Поля используются только внутри этой демонстрации.</p></div></div><form id="referralForm" class="form-grid"><div class="field"><label for="patientName">Имя пациента (можно с инициалом)</label><input id="patientName" required minlength="2" maxlength="40" placeholder="Например, Анна К."></div><div class="field"><label for="lastDigits">Последние 4 цифры телефона</label><input id="lastDigits" inputmode="numeric" pattern="[0-9]{4}" maxlength="4" required placeholder="0000"></div><div class="field"><label for="visitDate">Планируемая дата визита</label><input id="visitDate" type="date" required value="2026-09-24"></div><div class="field"><label for="direction">Направление</label><select id="direction"><option>Консультация офтальмолога</option><option>Диагностика зрения</option><option>Консультация хирурга</option><option>Детский офтальмолог</option></select></div><div class="hint full">Демонстрация не отправляет эти сведения в ГлазЦентр и не сохраняет их на сервере. Для реального запуска потребуется согласованный порядок передачи данных пациента и подтверждения его согласия.</div><div class="form-actions full"><button class="btn btn-primary" type="submit">Создать направление</button><span class="form-note">Созданная запись будет видна при переключении ролей, пока открыта эта страница.</span></div></form></section><section class="card"><h2>После отправки</h2><p class="sub">Статус меняется по мере обработки.</p><div class="steps"><div class="step"><span class="step-num">1</span><div><b>Направлен</b><p>Запись видна врачу-партнёру и команде ГлазЦентра.</p></div></div><div class="step"><span class="step-num">2</span><div><b>Пришёл</b><p>Врач ГлазЦентра отмечает посещение.</p></div></div><div class="step"><span class="step-num">3</span><div><b>Подтверждён</b><p>Администратор сверяет запись и включает её в расчёт.</p></div></div></div></section></div>`}
function filterControls(){let f=state.filters;return `<div class="filters"><div class="field"><label for="clinicFilter">Клиника</label><select id="clinicFilter" data-filter="clinic"><option value="all">Все клиники</option>${clinics.map(c=>`<option ${f.clinic===c?'selected':''} value="${esc(c)}">${esc(c)}</option>`).join('')}</select></div><div class="field"><label for="doctorFilter">Врач-партнёр</label><select id="doctorFilter" data-filter="doctor"><option value="all">Все врачи</option>${doctors.map(d=>`<option ${f.doctor===d?'selected':''} value="${esc(d)}">${esc(d)}</option>`).join('')}</select></div><div class="field"><label for="statusFilter">Статус</label><select id="statusFilter" data-filter="status"><option value="all">Все статусы</option>${Object.entries(statusText).map(([key,label])=>`<option ${f.status===key?'selected':''} value="${key}">${label}</option>`).join('')}</select></div><div class="field date-field"><label for="fromFilter">С</label><input id="fromFilter" type="date" data-filter="from" value="${f.from}"></div><div class="field date-field"><label for="toFilter">По</label><input id="toFilter" type="date" data-filter="to" value="${f.to}"></div><div class="field search-field"><label for="queryFilter">Поиск</label><input id="queryFilter" data-filter="query" placeholder="Номер, имя, последние цифры" value="${esc(f.query)}"></div></div>`}
function filtered(){let f=state.filters;return roleRows().filter(r=>(f.clinic==='all'||r.clinic===f.clinic)&&(f.doctor==='all'||r.doctor===f.doctor)&&(f.status==='all'||r.status===f.status)&&(!f.from||r.date>=f.from)&&(!f.to||r.date<=f.to)&&(!f.query||`${r.id} ${r.name} ${r.last}`.toLowerCase().includes(f.query.toLowerCase())))}
function listPage(){const partner=state.role==='partner',doc=state.role==='doctor';const title=partner?'Мои пациенты':doc?'Направленные пациенты':'Все направления';const sub=partner?'Отслеживайте путь пациента от направления до подтверждения.':doc?'Отмечайте реальный приход пациента после проверки записи.':'Просматривайте направления всех клиник и врачей.';return header(title,sub,partner?'<button class="btn btn-primary" data-tab="new">＋ Новое направление</button>':'')+`<section class="card"><div class="card-head"><div><h2>Список направлений</h2><p class="sub">Фильтрация по дате создания направления</p></div><button class="text-button" data-action="reset">Сбросить</button></div>${partner?'':filterControls()}<div id="listResults">${table(partner?roleRows():filtered(),doc?'doctor':partner?'view':'admin')}</div></section>`}
function reconcile(){const list=filtered(), eligible=confirmed(list), pending=list.filter(r=>r.status==='arrived'||r.status==='dispute');return header('Сверка направлений','Сопоставьте отправленные направления с фактическими визитами за выбранный период.','<button class="btn btn-outline" data-action="export">↓ Скачать CSV</button>','КОНТРОЛЬ ВИЗИТОВ')+`<section class="card"><div class="card-head"><div><h2>Пациенты и статусы</h2><p class="sub">Период определяется датой направления. Визит проверяется отдельно.</p></div><button class="text-button" data-action="reset">Сбросить</button></div>${filterControls()}<div class="grid-stats" style="margin:5px 0 15px">${stat('Направлено',list.length)}${stat('Подтверждено',eligible.length)}${stat('Нужно проверить',pending.length)}${stat('Расчётная сумма',money(eligible.length*1500),'Пример ставки 1 500 ₽',true)}</div><div id="listResults">${table(list,state.role==='admin'?'admin':'doctor')}</div></section><div class="hint section-gap">«Пришёл» означает отметку врача ГлазЦентра. «Подтверждён» появляется после проверки администратором. При расхождении начисление не создаётся.</div>`}
function payouts(){const list=roleRows(), names=state.role==='partner'?[doctors[0]]:doctors;return header(state.role==='partner'?'Вознаграждение':'Расчёт выплат','В демонстрации сумма рассчитана по подтверждённым визитам за сентябрь 2026 года.','', 'ФИНАНСЫ')+`<div class="grid-stats">${stat('Подтверждённые визиты',confirmed(list).length)}${stat('Ставка за визит',money(1500),'Условная ставка для демо')}${stat('Ожидают сверки',count(list,'arrived')+count(list,'dispute'))}${stat('К выплате',money(confirmed(list).length*1500),'Демонстрационный расчёт',true)}</div><div class="columns"><section class="card"><div class="card-head"><div><h2>По врачам-партнёрам</h2><p class="sub">Количество подтверждённых приходов</p></div></div><div class="table-wrap"><table class="data-table"><thead><tr><th>Врач</th><th>Клиника</th><th>Пришли</th><th>Подтверждено</th><th>Сумма</th></tr></thead><tbody>${names.map(n=>{let r=list.filter(x=>x.doctor===n);return `<tr><td><strong>${esc(n)}</strong></td><td>${esc(r[0]?.clinic||'—')}</td><td>${count(r,'arrived')+count(r,'verified')}</td><td>${count(r,'verified')}</td><td><strong>${money(count(r,'verified')*1500)}</strong></td></tr>`}).join('')}</tbody></table></div></section><section class="card"><h2>Правило расчёта</h2><p class="sub">Для обсуждения с руководством</p><div class="steps"><div class="step"><span class="step-num">✓</span><div><b>1 пациент = 1 подтверждённый визит</b><p>Повторный просмотр записи не увеличивает сумму.</p></div></div><div class="step"><span class="step-num">×</span><div><b>Неявка и расхождение</b><p>В выплату не включаются.</p></div></div></div><div class="hint">Размер, основание и порядок выплаты показаны условно. Финальные правила требуют согласования.</div></section></div>`}
function render(){nav();let html=state.tab==='home'?overview():state.tab==='new'?newReferral():state.tab==='reconcile'?reconcile():state.tab==='payouts'?payouts():listPage();el('main').innerHTML=html;syncTelegramBackButton()}
function refreshList(){if(!el('listResults'))return;el('listResults').innerHTML=table(filtered(),state.role==='admin'?'admin':'doctor');const cards=el('main').querySelector('.grid-stats');if(state.tab==='reconcile'&&cards){let l=filtered();cards.innerHTML=stat('Направлено',l.length)+stat('Подтверждено',confirmed(l).length)+stat('Нужно проверить',count(l,'arrived')+count(l,'dispute'))+stat('Расчётная сумма',money(confirmed(l).length*1500),'Пример ставки 1 500 ₽',true)}}
document.addEventListener('click',e=>{let role=e.target.closest('[data-role]'),tab=e.target.closest('[data-tab]'),action=e.target.closest('[data-action]');if(role){setRole(role.dataset.role);return}if(tab){setTab(tab.dataset.tab);return}if(e.target.closest('#roleButton')){let menu=el('roleMenu');menu.classList.toggle('hidden');el('roleButton').setAttribute('aria-expanded',String(!menu.classList.contains('hidden')));return}if(!e.target.closest('#roleMenu')){el('roleMenu').classList.add('hidden');el('roleButton').setAttribute('aria-expanded','false')}if(action){let a=action.dataset.action,r=rows.find(x=>x.id===action.dataset.id);if(a==='reset'){state.filters={clinic:'all',doctor:'all',status:'all',from:'2026-09-01',to:'2026-09-30',query:''};render()}if(a==='arrive'&&r){r.status='arrived';render();toast(`Приход по направлению ${r.id} отмечен. Ожидается сверка.`)}if(a==='verify'&&r){r.status='verified';render();toast(`Визит ${r.id} подтверждён и включён в расчёт.`)}if(a==='resolve'&&r){r.status='arrived';render();toast(`Запись ${r.id} возвращена на сверку. Проверьте фактический визит.`)}if(a==='export')exportCSV()}});
document.addEventListener('change',e=>{let f=e.target.dataset.filter;if(f){state.filters[f]=e.target.value;refreshList()}});
document.addEventListener('input',e=>{if(e.target.dataset.filter==='query'){state.filters.query=e.target.value;refreshList()}});
document.addEventListener('submit',e=>{if(e.target.id!=='referralForm')return;e.preventDefault();const name=el('patientName').value.trim(),last=el('lastDigits').value,visit=el('visitDate').value;if(!name||!/^\d{4}$/.test(last)||!visit)return;let next=String(Math.max(...rows.map(r=>Number(r.id.slice(2))))+1);rows.unshift({id:'Н-'+next,name,last,clinic:clinics[0],doctor:doctors[0],date:'2026-09-21',visit,status:'sent',reward:1500});setTab('patients');toast(`Направление Н-${next} создано в демоверсии.`)});
document.addEventListener('keydown',e=>{if(e.key==='Escape'){el('roleMenu').classList.add('hidden');el('roleButton').setAttribute('aria-expanded','false')}});
function exportCSV(){const list=filtered();const lines=[['Номер','Пациент','Последние 4 цифры','Клиника','Врач','Дата направления','Дата визита','Статус','Вознаграждение (демо)'],...list.map(r=>[r.id,r.name,r.last,r.clinic,r.doctor,r.date,r.visit,statusText[r.status],r.status==='verified'?r.reward:0])];let csv='\ufeff'+lines.map(line=>line.map(v=>'"'+String(v).replace(/"/g,'""')+'"').join(';')).join('\r\n');let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));a.download='glazcenter-reconciliation-demo.csv';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),5000);toast(`Скачано ${list.length} записей по текущим фильтрам.`)}
render();
if (telegram) telegram.BackButton.onClick(()=>setTab('home'));
// Optional browser agent controls mirror the visible demo actions.
if (document.modelContext?.registerTool) {
  const register = tool => { try { Promise.resolve(document.modelContext.registerTool(tool)).catch(()=>{}); } catch (_) {} };
  register({name:'switch_demo_role',title:'Сменить роль в демо',description:'Переключить видимый кабинет между врачом-партнёром, врачом ГлазЦентра и администратором.',inputSchema:{type:'object',properties:{role:{type:'string',enum:['partner','doctor','admin']}},required:['role'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute({role}){if(!roleInfo[role])throw Error('Неизвестная роль');setRole(role);return {role,visibleTitle:el('roleName').textContent}}});
  register({name:'create_demo_referral',title:'Создать тестовое направление',description:'Добавить вымышленное направление в текущую демосессию врача-партнёра. Никаких данных на сервер не отправляет.',inputSchema:{type:'object',properties:{patientName:{type:'string'},lastFourDigits:{type:'string',pattern:'^[0-9]{4}$'},visitDate:{type:'string',pattern:'^2026-[0-9]{2}-[0-9]{2}$'}},required:['patientName','lastFourDigits','visitDate'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute({patientName,lastFourDigits,visitDate}){if(state.role!=='partner')throw Error('Переключитесь на врача-партнёра');const name=String(patientName||'').trim();if(name.length<2||name.length>40||!/^\d{4}$/.test(lastFourDigits)||!/^2026-\d{2}-\d{2}$/.test(visitDate)||Number.isNaN(Date.parse(visitDate)))throw Error('Проверьте данные направления');const id='Н-'+(Math.max(...rows.map(r=>Number(r.id.slice(2))))+1);rows.unshift({id,name,last:lastFourDigits,clinic:clinics[0],doctor:doctors[0],date:'2026-09-21',visit:visitDate,status:'sent',reward:1500});setTab('patients');return {id,status:'Направлен'}}});
}
